### PR TITLE
FIX matching of confirmation page if called with params

### PR DESCRIPTION
**Pull request by Dominik2809**
### All changes meet the following requirements
- [x] Changelog entry was added
- [x] Changes have been tested by the author
- [x] Changes have been tested by the reviewer
- [x] Plugin can be built

@plentymarkets/ceres-io

### CODE REVIEW

**Comment by felixdausch** [comment]
Restart tests.

**Comment by plentymonkey** [comment]
Can one of the admins verify this patch?

**Comment by felixdausch** [comment]
Restart tests

**Review by felixdausch — APPROVED** [review]

**Comment by stentrop** [comment]
Restart tests

**Comment by felixdausch** [comment]
Restart tests

**Comment by felixdausch** [comment]
Restart tests

**Pull request merged**
