### PR TITLE
FIX guest order newsletter subscription

### PR DESCRIPTION
**Pull request by Dominik2809**
FIX address validator

### All changes meet the following requirements
- [x] Changelog entry was added
- [x] Changes have been tested
- [x] Plugin can be built

@plentymarkets/ceres-io

### CODE REVIEW

**Review by stentrop — DISMISSED** [review]

**Comment by Dominik2809** [comment]
Restart tests.

**Comment by Dominik2809** [comment]
Restart tests.

**Comment by Dominik2809** [comment]
Restart tests.

**Comment by Dominik2809** [comment]
Restart tests.

**Comment by lks-mtzn** [comment]
Restart tests.

**Pull request merged**
