### PR TITLE
add new order property

### PR DESCRIPTION
**Pull request by stentrop**
### All changes meet the following requirements
- [x] Changelog entry was added
- [x] Changes have been tested
- [x] Plugin can be built

@plentymarkets/ceres-io

### CODE REVIEW

**Comment by mdierkes** [comment]
Restart tests.

**Comment by mdierkes** [comment]
Restart tests.

**Comment by mdierkes** [comment]
Restart test.

**Comment by mdierkes** [comment]
Restart tests.

**Comment by mdierkes** [comment]
Restart tests.

**Comment by mdierkes** [comment]
Restart tests.

**Comment by mdierkes** [comment]
Restart tests.

**Comment by lks-mtzn** [comment]
Restart tests.

**Review by felixdausch — DISMISSED** [review]

**Review by felixdausch — APPROVED** [review]

**Comment by stentrop** [comment]
Restart test.

**Comment by stentrop** [comment]
Restart tests.

**Pull request merged**
