### PR TITLE
UPDATE handle new company input

### PR DESCRIPTION
**Pull request by Dominik2809**
### All changes meet the following requirements
- [x] Changelog entry was added
- [x] Changes have been tested
- [x] Plugin can be built

@plentymarkets/ceres-io

### CODE REVIEW

**Comment by Dominik2809** [comment]
Restart tests.

**Comment by Dominik2809** [comment]
Restart tests.

**Review by felixdausch — DISMISSED** [review]

**Comment by Dominik2809** [comment]
Restart tests.

**Comment by Dominik2809** [comment]
Restart tests.

**Review by felixdausch — APPROVED** [review]

**Pull request merged**
